# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from  mhyt  import  yt_download 
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_download = QtWidgets.QPushButton(self.centralwidget)
        self.bt_download.setGeometry(QtCore.QRect(270, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        self.bt_download.setFont(font)
        self.bt_download.setObjectName("bt_download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 210, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 250, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_link = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_link.setGeometry(QtCore.QRect(160, 210, 291, 21))
        self.txt_link.setText("")
        self.txt_link.setObjectName("txt_link")
        self.txt_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(160, 250, 291, 22))
        self.txt_titulo.setObjectName("txt_titulo")
        self.rb_mp3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_mp3.setGeometry(QtCore.QRect(140, 290, 57, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.rb_mp3.setFont(font)
        self.rb_mp3.setObjectName("rb_mp3")
        self.rb_mp4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_mp4.setGeometry(QtCore.QRect(200, 290, 61, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.rb_mp4.setFont(font)
        self.rb_mp4.setObjectName("rb_mp4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 130, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(26)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 120, 111, 71))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        ### Botão Download ###
        self.bt_download.clicked.connect(self.download)

    def download(self):
        if self.rb_mp4.isChecked() == True:
            url = self.txt_link.text()
            titulo = self.txt_titulo.text()
            titulo_mp4 = titulo + '.mp4'
            yt_download (url , titulo_mp4) 
        elif self.rb_mp3.isChecked() == True:
            try:
                url = self.txt_link.text()
                titulo = self.txt_titulo.text() 
                titulo_mp3 = titulo + '.mp3'
                yt_download (url , titulo_mp3, ismusic = True, codec = 'mp3')
            except:
                pass 



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_download.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Link"))
        self.label_2.setText(_translate("MainWindow", "Titulo"))
        self.rb_mp3.setText(_translate("MainWindow", "Mp3"))
        self.rb_mp4.setText(_translate("MainWindow", "Mp4"))
        self.label_3.setText(_translate("MainWindow", "Download"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/youtube/Youtube.png\"/></p></body></html>"))
import youtube


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
